### ISSUE TITLE
vecel 오류가 납니다.

### ISSUE THREAD

**Issue by rhsok** [Jinyang-Park/ProjectWalkTogether#171]
pull request시 vecel 오류가 납니다. 연결이 끊긴거 같네요

**Comment by Jinyang-Park** [comment]
확인해 보니 제대로 연결되어 있습니다. 채팅 반응형일 때 뒤로 가기 이모티콘이 나타나면서 뒤로 가기 기능을 추가하신 거죠? 모바일에서 정상 작동합니다! 다시 한번 확인해 보시죠

**Comment by GhostPines** [comment]
형선님

요즘도 개발중이시구나?




팩트인베스트
전략기획 팀장
김민성

010-8414-8680
***@***.***

2024. 4. 2. 16:11, 라형선 ***@***.***> 작성:

﻿

Closed #171<https://github.com/Jinyang-Park/ProjectWalkTogether/issues/171> as completed.
